[[datasets]]
batch_size = 4
bucket_no_upscale = true
enable_bucket = true
resolution = 512
keep_tokens = 1
caption_extension = '.txt'

[[datasets.subsets]]
image_dir = '/disk1/train/kotaro/train'
class_tokens = 'kotaro boy'
num_repeats = 1
# color_aug	 = true
flip_aug = true
random_crop = true
shuffle_caption = true

# [[datasets.subsets]]
# image_dir = '/disk1/train/kotaro/reg'
# is_reg = true
# class_tokens = 'girl'
# num_repeats = 1
# color_aug = false
# random_crop = false
# flip_aug = false
